version: '3'
services:
  lmnas-cms:
    image: lmnas/dumps:${VERSION}
    restart: always
    environment:
      APP_KEYS: ${APP_KEY}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_CLIENT: postgres
      DATABASE_HOST: lmnas-cmsDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: production
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.middlewares.prod-redirect.redirectscheme.scheme=https
        - traefik.http.routers.lmnasblog-http.rule=Host(`lmnasblog.docker.localhost`)
        - traefik.http.routers.lmnasblog-http.entrypoints=http
        - traefik.http.routers.lmnasblog-http.middlewares=prod-redirect
        - traefik.http.routers.lmnasblog-https.rule=Host(`lmnasblog.docker.localhost`)
        - traefik.http.routers.lmnasblog-https.entrypoints=https
        - traefik.http.routers.lmnasblog-https.tls=true
        - traefik.http.routers.lmnasblog-https.tls.certresolver=le
        - traefik.http.services.lmnasblog.loadbalancer.server.port=1337

    ports:
      - '1337:1337'
    networks:
      - lmnas-cms
      - traefik-public
    depends_on:
      - lmnas-cmsDB
      
  lmnas-cmsDB:
    restart: always
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - lmnas-cms-data:/var/lib/postgresql/data/

    ports:
      - '5432:5432'
    networks:
      - lmnas-cms
      
  lmnas-cmsAdminer:
    image: adminer
    restart: always
    ports:
      - '9090:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=lmnas-cmsDB
    networks:
      - lmnas-cms
    depends_on:
      - lmnas-cmsDB

volumes:
  lmnas-cms-data:

networks:
  traefik-public:
    external: true
  lmnas-cms:
    external: false
